<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.0.123" />
    <PackageReference Include="EPPlus" Version="7.0.4" />
    <PackageReference Include="itext7" Version="9.0.0" />
    <PackageReference Include="iTextSharp" Version="5.5.13.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.1" />
    <PackageReference Include="PdfiumViewer" Version="2.13.0" />
    <PackageReference Include="Spire.PDF" Version="10.11.7" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Prisma.Common\MDFusionLabHaute.Common.csproj" />
  </ItemGroup>
</Project>