//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDFusionLabHaute.DesktopSurface.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ENGLanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ENGLanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDFusionLabHaute.DesktopSurface.LanguageResources.ENGLanguageResource", typeof(ENGLanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .00 ML.
        /// </summary>
        public static string _00_ML {
            get {
                return ResourceManager.GetString(".00 ML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD X DROP/S OF ESSENCE X.
        /// </summary>
        public static string ADD_X_DROP_S_OF_ESSENCE_X {
            get {
                return ResourceManager.GetString("ADD X DROP/S OF ESSENCE X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        public static string BACK {
            get {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITY.
        /// </summary>
        public static string CITY {
            get {
                return ResourceManager.GetString("CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTANT ID.
        /// </summary>
        public static string CONSULTANT_ID {
            get {
                return ResourceManager.GetString("CONSULTANT ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTANT PASSWORD.
        /// </summary>
        public static string CONSULTANT_PASSWORD {
            get {
                return ResourceManager.GetString("CONSULTANT PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMER.
        /// </summary>
        public static string CUSTOMER {
            get {
                return ResourceManager.GetString("CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DERMAPROFILE™.
        /// </summary>
        public static string DERMAPROFILE {
            get {
                return ResourceManager.GetString("DERMAPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISPENSE.
        /// </summary>
        public static string DISPENSE {
            get {
                return ResourceManager.GetString("DISPENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DISPENSING___ {
            get {
                return ResourceManager.GetString("DISPENSING...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGRAVING LINE 1.
        /// </summary>
        public static string ENGRAVING_LINE_1 {
            get {
                return ResourceManager.GetString("ENGRAVING LINE 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGRAVING LINE 2.
        /// </summary>
        public static string ENGRAVING_LINE_2 {
            get {
                return ResourceManager.GetString("ENGRAVING LINE 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT.
        /// </summary>
        public static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRST NAME.
        /// </summary>
        public static string FIRST_NAME {
            get {
                return ResourceManager.GetString("FIRST NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORWARD.
        /// </summary>
        public static string FORWARD {
            get {
                return ResourceManager.GetString("FORWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LABELING LANGUAGE.
        /// </summary>
        public static string LABELING_LANGUAGE {
            get {
                return ResourceManager.GetString("LABELING LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST NAME.
        /// </summary>
        public static string LAST_NAME {
            get {
                return ResourceManager.GetString("LAST NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCK.
        /// </summary>
        public static string LOCK {
            get {
                return ResourceManager.GetString("LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACHINE REG NO.
        /// </summary>
        public static string MACHINE_REG_NO {
            get {
                return ResourceManager.GetString("MACHINE REG NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACHINE REGISTRATION NUMBER.
        /// </summary>
        public static string MACHINE_REGISTRATION_NUMBER {
            get {
                return ResourceManager.GetString("MACHINE REGISTRATION NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODE.
        /// </summary>
        public static string MODE {
            get {
                return ResourceManager.GetString("MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE CONFIRM EVERYTHING IS READY FOR THE NEXT DISPENSE..
        /// </summary>
        public static string NEXT_DISPENSE_MESSAGE {
            get {
                return ResourceManager.GetString("NEXT DISPENSE MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAUSA.
        /// </summary>
        public static string PAUSE {
            get {
                return ResourceManager.GetString("PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONALIZED SERUM CONCENTRATE CREATED.
        /// </summary>
        public static string PERSONALIZED_SERUM_CONCENTRATE_CREATED {
            get {
                return ResourceManager.GetString("PERSONALIZED SERUM CONCENTRATE CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLACE BOTTLE IN DOCK.
        /// </summary>
        public static string PLACE_BOTTLE_IN_DOCK {
            get {
                return ResourceManager.GetString("PLACE BOTTLE IN DOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINT.
        /// </summary>
        public static string PRINT {
            get {
                return ResourceManager.GetString("PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINTING....
        /// </summary>
        public static string PRINTING___ {
            get {
                return ResourceManager.GetString("PRINTING...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCTION.
        /// </summary>
        public static string PRODUCTION {
            get {
                return ResourceManager.GetString("PRODUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPEAT DERMAPROFILE™.
        /// </summary>
        public static string REPEAT_DERMAPROFILE_tm {
            get {
                return ResourceManager.GetString("REPEAT DERMAPROFILE tm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPEAT TAILORING CODE.
        /// </summary>
        public static string REPEAT_TAILORING_CODE {
            get {
                return ResourceManager.GetString("REPEAT TAILORING CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTART.
        /// </summary>
        public static string RESTART {
            get {
                return ResourceManager.GetString("RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCANNER.
        /// </summary>
        public static string SCANNER {
            get {
                return ResourceManager.GetString("SCANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT AMOUNT.
        /// </summary>
        public static string SELECT_AMOUNT {
            get {
                return ResourceManager.GetString("SELECT AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CAN SIZE.
        /// </summary>
        public static string SELECT_CAN_SIZE {
            get {
                return ResourceManager.GetString("SELECT CAN SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ESSENCE.
        /// </summary>
        public static string SELECT_ESSENCE {
            get {
                return ResourceManager.GetString("SELECT ESSENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT NO OF QUANTITY.
        /// </summary>
        public static string SELECT_NO_OF_QUANTITY {
            get {
                return ResourceManager.GetString("SELECT NO OF QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT PRODUCT.
        /// </summary>
        public static string SELECT_PRODUCT {
            get {
                return ResourceManager.GetString("SELECT PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOP ADDRESS.
        /// </summary>
        public static string SHOP_ADDRESS {
            get {
                return ResourceManager.GetString("SHOP ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOP NAME.
        /// </summary>
        public static string SHOP_NAME {
            get {
                return ResourceManager.GetString("SHOP NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATE.
        /// </summary>
        public static string STATE {
            get {
                return ResourceManager.GetString("STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAILORING CODE.
        /// </summary>
        public static string TAILORING_CODE {
            get {
                return ResourceManager.GetString("TAILORING CODE", resourceCulture);
            }
        }
    }
}
