//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDFusionLabHaute.DesktopSurface.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ESPLanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ESPLanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDFusionLabHaute.DesktopSurface.LanguageResources.ESPLanguageResource", typeof(ESPLanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .00 ML.
        /// </summary>
        public static string _00_ML {
            get {
                return ResourceManager.GetString(".00 ML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AÑADIR X GOTA/S DE ESENCIA X.
        /// </summary>
        public static string ADD_X_DROP_S_OF_ESSENCE_X {
            get {
                return ResourceManager.GetString("ADD X DROP/S OF ESSENCE X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATRÁS.
        /// </summary>
        public static string BACK {
            get {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIUDAD.
        /// </summary>
        public static string CITY {
            get {
                return ResourceManager.GetString("CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID CONSULTOR.
        /// </summary>
        public static string CONSULTANT_ID {
            get {
                return ResourceManager.GetString("CONSULTANT ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRASEÑA DEL CONSULTOR.
        /// </summary>
        public static string CONSULTANT_PASSWORD {
            get {
                return ResourceManager.GetString("CONSULTANT PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLIENTE.
        /// </summary>
        public static string CUSTOMER {
            get {
                return ResourceManager.GetString("CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DERMAPROFILE™.
        /// </summary>
        public static string DERMAPROFILE {
            get {
                return ResourceManager.GetString("DERMAPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISPENSAR.
        /// </summary>
        public static string DISPENSE {
            get {
                return ResourceManager.GetString("DISPENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DISPENSING___ {
            get {
                return ResourceManager.GetString("DISPENSING...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LÍNEA DE GRABADO 1.
        /// </summary>
        public static string ENGRAVING_LINE_1 {
            get {
                return ResourceManager.GetString("ENGRAVING LINE 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LÍNEA DE GRABADO 2.
        /// </summary>
        public static string ENGRAVING_LINE_2 {
            get {
                return ResourceManager.GetString("ENGRAVING LINE 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALIR.
        /// </summary>
        public static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOMBRE.
        /// </summary>
        public static string FIRST_NAME {
            get {
                return ResourceManager.GetString("FIRST NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADELANTE.
        /// </summary>
        public static string FORWARD {
            get {
                return ResourceManager.GetString("FORWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LENGUAJE DE ETIQUETADO.
        /// </summary>
        public static string LABELING_LANGUAGE {
            get {
                return ResourceManager.GetString("LABELING LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APELLIDO.
        /// </summary>
        public static string LAST_NAME {
            get {
                return ResourceManager.GetString("LAST NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOQUEAR.
        /// </summary>
        public static string LOCK {
            get {
                return ResourceManager.GetString("LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NÚMERO DE REGISTRO DE LA MÁQUINA.
        /// </summary>
        public static string MACHINE_REG_NO {
            get {
                return ResourceManager.GetString("MACHINE REG NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NÚMERO DE REGISTRO DE LA MÁQUINA.
        /// </summary>
        public static string MACHINE_REGISTRATION_NUMBER {
            get {
                return ResourceManager.GetString("MACHINE REGISTRATION NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODO.
        /// </summary>
        public static string MODE {
            get {
                return ResourceManager.GetString("MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRME QUE TODO ESTÉ LISTO PARA LA SIGUIENTE DISPENSACIÓN..
        /// </summary>
        public static string NEXT_DISPENSE_MESSAGE {
            get {
                return ResourceManager.GetString("NEXT DISPENSE MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAUSA.
        /// </summary>
        public static string PAUSE {
            get {
                return ResourceManager.GetString("PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERUM CONCENTRADO PERSONALIZADO CREADO.
        /// </summary>
        public static string PERSONALIZED_SERUM_CONCENTRATE_CREATED {
            get {
                return ResourceManager.GetString("PERSONALIZED SERUM CONCENTRATE CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLOCAR BOTELLA EN LA BANDEJA.
        /// </summary>
        public static string PLACE_BOTTLE_IN_DOCK {
            get {
                return ResourceManager.GetString("PLACE BOTTLE IN DOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPRIMIR.
        /// </summary>
        public static string PRINT {
            get {
                return ResourceManager.GetString("PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPRIMIENDO....
        /// </summary>
        public static string PRINTING___ {
            get {
                return ResourceManager.GetString("PRINTING...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCCIÓN.
        /// </summary>
        public static string PRODUCTION {
            get {
                return ResourceManager.GetString("PRODUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPETIR DERMAPROFILE™.
        /// </summary>
        public static string REPEAT_DERMAPROFILE_tm {
            get {
                return ResourceManager.GetString("REPEAT DERMAPROFILE tm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPETIR TAILORING CODE.
        /// </summary>
        public static string REPEAT_TAILORING_CODE {
            get {
                return ResourceManager.GetString("REPEAT TAILORING CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REINICIAR.
        /// </summary>
        public static string RESTART {
            get {
                return ResourceManager.GetString("RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESCÁNER.
        /// </summary>
        public static string SCANNER {
            get {
                return ResourceManager.GetString("SCANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT AMOUNT.
        /// </summary>
        public static string SELECT_AMOUNT {
            get {
                return ResourceManager.GetString("SELECT AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECCIONE ENVASE.
        /// </summary>
        public static string SELECT_CAN_SIZE {
            get {
                return ResourceManager.GetString("SELECT CAN SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECCIONAR ESENCIA.
        /// </summary>
        public static string SELECT_ESSENCE {
            get {
                return ResourceManager.GetString("SELECT ESSENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECCIONE CANTIDAD.
        /// </summary>
        public static string SELECT_NO_OF_QUANTITY {
            get {
                return ResourceManager.GetString("SELECT NO OF QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECCIONAR PRODUCTO.
        /// </summary>
        public static string SELECT_PRODUCT {
            get {
                return ResourceManager.GetString("SELECT PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIRECCIÓN DE LA TIENDA.
        /// </summary>
        public static string SHOP_ADDRESS {
            get {
                return ResourceManager.GetString("SHOP ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOMBRE DE TIENDA.
        /// </summary>
        public static string SHOP_NAME {
            get {
                return ResourceManager.GetString("SHOP NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTADO.
        /// </summary>
        public static string STATE {
            get {
                return ResourceManager.GetString("STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAILORING CODE.
        /// </summary>
        public static string TAILORING_CODE {
            get {
                return ResourceManager.GetString("TAILORING CODE", resourceCulture);
            }
        }
    }
}
